= GET1033 Project Summary
:site-section: ProjectPortfolio
:toc:
:toc-title:
:sectnums:
:imagesDir: docs/images
:stylesDir: docs/stylesheets
:xrefstyle: full

:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
:experimental:
= Automated Lighting & Doorbell/Alarm System

== Project Objectives
This project is assessed as the `Final Project` for GET1033, a module offered in the National University of Singapore (NUS). The purpose of this project is to explore computational media literacy by designing a project that involves the use of computational processes, including the use of actual programming. 

== Project Overview
As such, my project groupmates and I have decided to do a simple Arduino-based project, which models after an automated lighting and doorbell (or alarm) system. This allows us to make use of the abilities that computers affords us enables us to automate things that are otherwise inconvenient to do manually. Typically, for projects involving an automated lighting system, lights are activated when the environment is not bright enough, and when a person walks past the sensor. For our project, we tried to one-up this - to make the light follow the person's movements!

This involves the use of an Arduino board (Arduino Uno with an ATMega328P microcontroller), and the use of the C++ programming language together with the Arduino software and IDE. It also involves the use of hardware components such as sensors and actuators (details of how these components were implemented is discussed in the `Full Documentation` link below) - a light sensor component that determines the brightness of the surroundings, a proximity sensor that determines the distance of the person/object from the door, an LED and a servo to implement the moving lamp as well as a piezo buzzer for the alarm. 

== Useful Links

Refer to the link below for more details about this project and the documentation of the project development process.

* link:docs/ProjectDocumentation.adoc[Project Documentation]
* link:docs/images[Images & Videos]
* link:src[Source Code]

== Contributors

The members of the group can be found link:docs/AboutUs.adoc[here]
