= GET1033 Project Summary
:site-section: ProjectPortfolio
:toc:
:toc-title:
:sectnums:
:imagesDir: docs/images
:stylesDir: docs/stylesheets
:xrefstyle: full

:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
:experimental:
= Automated Lighting System & Doorbell/Alarm

== Project Objectives
This project is assessed as the `Final Project` for GET1033, a module offered in the National University of Singapore (NUS). The purpose of this project is to explore computational media literacy by designing a project that involves the use of computational processes, including the use of actual programming. 

== Project Overview
As such, my project group and I have decided to do a simple Arduino-based project, which models after an automated lighting and doorbell (or alarm) system. This involves the use of an Arduino board (Arduino Uno with an ATMega328P microcontroller), and the use of the C++ programming language together with the Arduino software and IDE. It also involves the use of hardware components such as sensors and actuators (explained more below).

Typically, an automated lighting system activates when the environment is not bright enough, and when a person walks past the sensor. For our project, we tried to one-up this: to make the light follow the person!

*Link for Documentation*

Refer to the link below for more details about this project and the documentation of the project development process.

* link:docs/images/ProjectDocumentation.adoc[Project Documentation]

== Contributors

The members of the group can be found link:docs/AboutUs.adoc[here]